version: '3.7'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./php-fpm
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
            - ./build.sh:/var/www/build.sh
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./symfony:/var/www/symfony
            - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "8025:8025"

volumes:
    db_data:
